# note: change the request header below
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-configs
  labels:
    app: manageiq
data:
  application.conf: |
    Listen 8080
    # Timeout: The number of seconds before receives and sends time out.
    Timeout 120

    RewriteEngine On
    Options SymLinksIfOwnerMatch

    <VirtualHost *:8080>
      KeepAlive on
      # Without ServerName mod_auth_mellon compares against http:// and not https:// from the IdP
      ServerName https://%{REQUEST_HOST}

      # NOTE #############################################
      # change host name to the host name used in the ingress obj
      ####################################################
      ProxyPreserveHost on
      RequestHeader set Host manageiq.devk8s2.yourcompany.com
      RequestHeader set X-Forwarded-Host manageiq.devk8s2.yourcompany.com

      RewriteCond %{REQUEST_URI}     ^/ws/notifications [NC]
      RewriteCond %{HTTP:UPGRADE}    ^websocket$ [NC]
      RewriteCond %{HTTP:CONNECTION} ^Upgrade$   [NC]
      RewriteRule .* ws://ui:3000%{REQUEST_URI}  [P,QSA,L]
      ProxyPassReverse /ws/notifications ws://ui:3000/ws/notifications

      RewriteCond %{REQUEST_URI} !^/api

      # For httpd, some ErrorDocuments must by served by the httpd pod
      RewriteCond %{REQUEST_URI} !^/proxy_pages

      # For OpenID-Connect /openid-connect is only served by mod_auth_openidc
      RewriteCond %{REQUEST_URI} !^/openid-connect

      RewriteRule ^/ http://ui:3000%{REQUEST_URI} [P,QSA,L]
      ProxyPassReverse / http://ui:3000/

      ProxyPass /api http://web-service:3000/api
      ProxyPassReverse /api http://web-service:3000/api

      RewriteCond %{REQUEST_URI}     ^/ws/console [NC]
      RewriteCond %{HTTP:UPGRADE}    ^websocket$  [NC]
      RewriteCond %{HTTP:CONNECTION} ^Upgrade$    [NC]
      RewriteRule .* ws://remote-console:3000%{REQUEST_URI}  [P,QSA,L]
      ProxyPassReverse /ws/console ws://remote-console:3000/ws/console

      # Ensures httpd stdout/stderr are seen by 'docker logs'.
      ErrorLog  "| /usr/bin/tee /proc/1/fd/2 /var/log/httpd/error_log"
      CustomLog "| /usr/bin/tee /proc/1/fd/1 /var/log/httpd/access_log" common
    </VirtualHost>
#