# hostname should match postgresql svc name
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  labels:
    app: manageiq
stringData:
  dbname: 'vmdb_production'
  hostname: 'postgresql'
  password: 'postgresql'
  username: 'root'
  port: '5432'

