apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manageiq-orchestrator
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs: ["get","watch","list","create","delete","patch"]
# - apiGroups:
#   - ''  
#   resources:
#   - pods/finalizers
#   verbs: ["watch"]  
#
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get","watch","list","create","delete","patch"]
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs: ["get","watch","list","create","delete","patch"]  
#
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs: ["get","watch","list","create","delete","patch"]
- apiGroups:
  - extensions
  resources:
  - deployments/scale
  verbs: ["get","watch","list","create","delete","patch"]