
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manageiq-orchestrator
roleRef:
  kind: Role
  name: manageiq-orchestrator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: manageiq-orchestrator

